### ISSUE TITLE
Issue with URLs

### ISSUE THREAD

**Issue by Thomas-Kim** [Thomas-Kim/truth-tables#28]
| turns into %7C

> turns into %3E

etc.

**Comment by georgiastuart** [comment]
I'm also having this issue with -> turning into %3E and not working.

**Comment by Thomas-Kim** [comment]
Hi, thanks for your interest in truth-tables.

I will be fixing this issue shortly, but it may take a little while to get the changes deployed to the public website.

**Comment by Thomas-Kim** [comment]
This issue was fixed in commit 39bc8d83080314d7366693de566e949d73303007
